CREATE TABLE USERS (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE ACCOUNT (
  id UUID PRIMARY KEY,
  account_number TEXT UNIQUE NOT NULL,
  agency TEXT NOT NULL,
  balance NUMERIC DEFAULT 0,
  user_id UUID REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE TRANSACTION (
  id UUID PRIMARY KEY,
  type_transaction VARCHAR(20) CHECK (type_transaction IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER_IN', 'TRANSFER_OUT', 'INVEST')),
  amount NUMERIC NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  description TEXT,
  account_id UUID REFERENCES ACCOUNT(id) ON DELETE CASCADE
);

CREATE TABLE INVESTIMENT(
  id UUID PRIMARY KEY,
  amount NUMERIC NOT NULL,
  start_date DATE DEFAULT CURRENT_DATE,
  end_date DATE DEFAULT CURRENT_DATE,
  account_id UUID REFERENCES ACCOUNT(id) ON DELETE CASCADE,
  invest_product_id UUID REFERENCES INVESTMENT_PRODUCT(id) ON DELETE CASCADE
);

CREATE TABLE INVESTMENT_PRODUCT(
    id UUID PRIMARY KEY,
    type_investiment VARCHAR(20) CHECK (type_investiment IN ('CDB', 'TESOURO', 'POUPANÇA')),
    return_rate NUMERIC NOT NULL
);
CREATE TABLE INVESTMENT_TRANSACTION (
  id UUID PRIMARY KEY,
  type VARCHAR(20) CHECK (type IN ('INVEST', 'REDEEM', 'EARN')),
  amount NUMERIC NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  investment_id UUID REFERENCES INVESTIMENT(id) ON DELETE CASCADE,
  description TEXT
);

